version: "2"

engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3

exclude_patterns:
  - config/
  - docs/
  - compose/
  - locale/
  - "**/tests/"
  - "**/migrations/"
  - ".*"
  - "*.*"
  - LICENSE
