sudo: required
language: python
python: "3.6"

services:
  - docker

env:
  - COMPOSE_FILE=local.yml PROJECT_NAME=mtg_deckbuilder

install:
  - docker-compose --project-name=$PROJECT_NAME up --detach --build
  - docker ps --all

before_script:
  - wget https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 --output-document=./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - docker cp ./cc-test-reporter $PROJECT_NAME_django_1:./cc-test-reporter
  - docker-compose exec django ./cc-test-reporter before-build

script:
  - docker-compose exec django /entrypoint pytest --cov=mtg_deckbuilder

after_script:
  - docker-compose exec django ./cc-test-reporter after-build --id=$CC_TEST_REPORTER_ID --exit-code $TRAVIS_TEST_RESULT
