sudo: required
language: python

services:
  - docker

env:
  - COMPOSE_FILE=local.yml

install:
  - docker-compose build
  - docker-compose up -d
  - docker ps -a
script:
  - docker-compose run django pytest

after_script:
  - docker-compose down
