sudo: required
language: python

services:
  - docker

env:
  - COMPOSE_FILE=production.yml

before_install:
  - docker-compose build
install:
  - docker-compose up
script:
  - docker-compose run django pytest
