sudo: required
language: python
python: "3.6"

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.21.2 COMPOSE_FILE=local.yml PROJECT_NAME=deckbuilder

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo wget https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` --output-document=/usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker --version
  - docker-compose --version

install:
  - docker-compose --project-name=${PROJECT_NAME} up --detach --build
  - docker ps --all

before_script:
  - wget https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 --output-document=./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - docker cp ./cc-test-reporter ${PROJECT_NAME}_django_1:./cc-test-reporter
  - docker-compose exec django ./cc-test-reporter before-build

script:
  - docker-compose exec django /entrypoint pytest --cov=mtg_deckbuilder --cov-report=xml --cov-report=term

after_script:
  - docker-compose exec django ./cc-test-reporter after-build --id=${CC_TEST_REPORTER_ID} --prefix=/app --exit-code ${TRAVIS_TEST_RESULT}
