sudo: required
language: python
python: "3.6"

services:
  - docker

env:
  - COMPOSE_FILE=local.yml

install:
  - docker-compose build django --build-arg EXTRA=test
  - docker-compose build
  - docker-compose up -d
  - docker ps -a
script:
  - docker-compose run django pytest --cov=mtg_deckbuilder --cov-report=xml

after_success:
  - docker cp mtg_deckbuilder_django_run_1:/app/coverage.xml ./coverage.xml

after_script:
  - docker-compose down
