sudo: required
language: python
python: "3.6"

services:
  - docker

env:
  - COMPOSE_FILE=local.yml

install:
  - docker-compose build --build-arg EXTRAS=test django
  - docker-compose build
  - docker-compose up -d
  - docker ps -a
script:
  - docker-compose exec django /entrypoint pytest --cov=mtg_deckbuilder

after_success:
  - docker-compose exec django /entrypoint codecov
