sudo: required
language: python
python: "3.6"

services:
  - docker

env:
  - COMPOSE_FILE=local.yml

install:
  - docker-compose build --build-args=test
  - docker-compose up -d
  - docker ps -a
  - docker-compose run django pytest --cov=mtg_deckbuilder --cov-report=xml
script:
  - pytest --cov=mtg_deckbuilder --cov-report=xml

after_script:
  - docker cp mtg_deckbuilder_django_run_1:/app/coverage.xml ./coverage.xml
  - docker-compose down
