# Generated by Django 2.0.6 on 2018-06-15 20:34

import django.contrib.postgres.fields
from django.db import migrations, models
import mtg_deckbuilder.cards.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('W', mtg_deckbuilder.cards.models.Color('W')), ('U', mtg_deckbuilder.cards.models.Color('U')), ('B', mtg_deckbuilder.cards.models.Color('B')), ('R', mtg_deckbuilder.cards.models.Color('R')), ('G', mtg_deckbuilder.cards.models.Color('G'))], max_length=1), size=None)),
                ('color_identity', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('W', mtg_deckbuilder.cards.models.Color('W')), ('U', mtg_deckbuilder.cards.models.Color('U')), ('B', mtg_deckbuilder.cards.models.Color('B')), ('R', mtg_deckbuilder.cards.models.Color('R')), ('G', mtg_deckbuilder.cards.models.Color('G'))], max_length=1), size=None)),
                ('cmc', models.DecimalField(decimal_places=1, max_digits=4)),
                ('card_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Basic', mtg_deckbuilder.cards.models.CardType('Basic')), ('Legendary', mtg_deckbuilder.cards.models.CardType('Legendary')), ('Ongoing', mtg_deckbuilder.cards.models.CardType('Ongoing')), ('Snow', mtg_deckbuilder.cards.models.CardType('Snow')), ('World', mtg_deckbuilder.cards.models.CardType('World')), ('Artifact', mtg_deckbuilder.cards.models.CardType('Artifact')), ('Conspiracy', mtg_deckbuilder.cards.models.CardType('Conspiracy')), ('Creature', mtg_deckbuilder.cards.models.CardType('Creature')), ('Enchantment', mtg_deckbuilder.cards.models.CardType('Enchantment')), ('Instant', mtg_deckbuilder.cards.models.CardType('Instant')), ('Land', mtg_deckbuilder.cards.models.CardType('Land')), ('Phenomenon', mtg_deckbuilder.cards.models.CardType('Phenomenon')), ('Plane', mtg_deckbuilder.cards.models.CardType('Plane')), ('Planeswalker', mtg_deckbuilder.cards.models.CardType('Planeswalker')), ('Scheme', mtg_deckbuilder.cards.models.CardType('Scheme')), ('Sorcery', mtg_deckbuilder.cards.models.CardType('Sorcery')), ('Tribal', mtg_deckbuilder.cards.models.CardType('Tribal')), ('Vanguard', mtg_deckbuilder.cards.models.CardType('Vanguard'))], max_length=16), size=None)),
                ('sub_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, size=None)),
                ('uri', models.URLField()),
                ('scryfall_uri', models.URLField()),
            ],
        ),
    ]
