# Generated by Django 2.0.6 on 2018-06-13 18:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[('Artifact', 'Artifact'), ('Conspiracy', 'Conspiracy'), ('Creature', 'Creature'), ('Enchantment', 'Enchantment'), ('Instant', 'Instant'), ('Land', 'Land'), ('Phenomenon', 'Phenomenon'), ('Plane', 'Plane'), ('Planeswalker', 'Planeswalker'), ('Scheme', 'Scheme'), ('Sorcery', 'Sorcery'), ('Tribal', 'Tribal'), ('Vanguard', 'Vanguard')]), size=None),
        ),
        migrations.AlterField(
            model_name='card',
            name='super_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[('Basic', 'Basic'), ('Legendary', 'Legendary'), ('Ongoing', 'Ongoing'), ('Snow', 'Snow'), ('World', 'World')]), size=None),
        ),
    ]
